theme: bulma-clean-theme
title: Book Blender
google_analytics: UA-4644630-2
baseurl: /book-blender
repository: donkirkby/book-blender

defaults:
  - scope:
      path: ""
    values:
      layout: page
      hero_image: /book-blender/images/index_hero.jpg
      hero_darken: true
      twitter:
        card: summary_large_image
      image: images/index_hero.jpg

plugins:
  - "jekyll-github-metadata"
