# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  - push
  - pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip pipenv
        pipenv install
    - name: Test with mypy and pytest
      id: test
      env:
        PYTHONPATH: .
      run: |
        pipenv run mypy --install-types --non-interactive .
        pipenv run pytest
    - name: Upload image diffs
      uses: actions/upload-artifact@v2
      if: ${{ always() && steps.test.outcome == 'failure' }}
      with:
        name: image-diffs
        path: |
          test/image_diffs/*.png
          test/image_diffs/*.svg
